"""補正係数の定数。根拠は docs/CALCULATION_LOGIC.md を参照。"""

# 基礎集客力: 直近を重視する指数減衰の係数（直近=1, 1つ前=DECAY, 2つ前=DECAY^2 ...）
ATTENDANCE_DECAY = 0.6

# 完売公演の censored data 補正
SOLD_OUT_BASE_CORRECTION = 1.05
SOLD_OUT_EARLY_BONUS_PER_DAY = 0.01
SOLD_OUT_CORRECTION_CAP = 1.20

# 価格弾力性（ルールベース、過去データからは学習しない）
PRICE_ELASTICITY = 0.9
PRICE_FACTOR_MIN = 0.4
PRICE_FACTOR_MAX = 1.3

# 曜日・時間帯・企画属性補正
WEEKEND_HOLIDAY_FACTOR = 1.08
EVENING_FACTOR = 1.05
NEW_WORK_FACTOR = 1.05
RARITY_FACTOR = {"low": 1.00, "mid": 1.05, "high": 1.12}
GUEST_FACTOR = 1.07
SPECIAL_FACTOR = 1.10

# 立地・会場ブランド補正
LOCATION_BASE = 0.90
LOCATION_RATING_STEP = 0.02
LOCATION_WALK_PENALTY_PER_MIN = 0.004
LOCATION_FACTOR_MIN = 0.85
LOCATION_FACTOR_MAX = 1.15

BRAND_BASE = 0.95
BRAND_RATING_STEP = 0.02
BRAND_FACTOR_MIN = 0.90
BRAND_FACTOR_MAX = 1.15

# SNS補正（補助情報。過大評価を防ぐため上限をキャップ）
SNS_WEIGHT_X = 1.0
SNS_WEIGHT_INSTAGRAM = 1.0
SNS_WEIGHT_YOUTUBE = 1.2
SNS_WEIGHT_OTHER = 0.5
SNS_FACTOR_SCALE = 0.006
SNS_FACTOR_CAP = 0.05

# 公演回数の逓減モデル（観客プールの重複を考慮）
POOL_EXPONENT = 0.85

# 価格探索の刻み幅
PRICE_STEP = 100

# Venue Fit 判定の稼働率しきい値
VENUE_FIT_TOO_SMALL_THRESHOLD = 1.00
VENUE_FIT_GOOD_MIN = 0.75
VENUE_FIT_SLIGHTLY_LARGE_MIN = 0.55

# 満席重視の目標稼働率下限
SELLOUT_TARGET_OCCUPANCY = 0.90

# バランススコアの重み
BALANCE_WEIGHT_OCCUPANCY = 0.30
BALANCE_WEIGHT_REVENUE = 0.30
BALANCE_WEIGHT_PROFIT = 0.30
BALANCE_WEIGHT_DISCOUNT_PENALTY = 0.10
BALANCE_TARGET_OCCUPANCY_RANGE = (0.85, 0.97)

# 推奨価格帯: バランススコアの何%以内を「帯」に含めるか
RECOMMENDED_RANGE_SCORE_THRESHOLD = 0.95

MODEL_VERSION = "rule_v0.1"
